name: fox
description: A new Flutter project.
version: 1.0.0+1
environment: 
#  sdk: '>=2.17.0 <3.0.0'
   sdk: ">=3.0.0 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter_login_facebook: ^1.9.0
  flutter_facebook_auth: ^7.0.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  flutter_feather_icons: ^2.0.0+1
  font_awesome_flutter: ^10.7.0
  image_picker: ^0.8.7+5
  path_provider: ^2.1.3
  image: ^3.0.2
  photofilters:
    path: photofilters-3.0.1
  image_cropper: ^5.0.1
  image_editor: ^1.5.1
  google_fonts: ^6.2.1
  screenshot: ^3.0.0
  gal: ^2.3.0
  http: ^1.2.1

dev_dependencies:
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: true
  image_path: "assets/images/img_icon_fox.png"
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/sticker/
    - assets/sticker/food/
    - assets/sticker/hiphop/
